### ISSUE TITLE
Error when running Create Database Tables command from palette

### ISSUE THREAD

**Issue by jrkoiter** [andriyko/sublime-robot-framework-assistant#170]
I'm on Mac 10.11.6, Sublime 3 build 3126. Error I get in console is:
`See log file from database directory for details
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "/Users/joost/Library/Application Support/Sublime Text 3/Packages/Robot Framework Assistant/commands/scan.py", line 40, in run
    sublime.set_timeout_async(self.run_scan(file_), 0)
  File "/Users/joost/Library/Application Support/Sublime Text 3/Packages/Robot Framework Assistant/commands/scan.py", line 60, in run_scan
    raise ValueError('Error in scanning result code: {0}'.format(rc))
ValueError: Error in scanning result code: 1`

**Comment by jrkoiter** [comment]
Needed to specify robot_framework_workspace and path_to_python
