### ISSUE TITLE
Create database tables fails - pyenv

### ISSUE THREAD

**Issue by megachips** [andriyko/sublime-robot-framework-assistant#224]
Hi there, on OSX 10.14.1,

I can't create database tables. Get the usual error.

`Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "/Users/davew/Library/Application Support/Sublime Text 3/Packages/RobotFrameworkAssistant/commands/scan.py", line 41, in run
    sublime.set_timeout_async(self.run_scan(file_), 0)
  File "/Users/davew/Library/Application Support/Sublime Text 3/Packages/RobotFrameworkAssistant/commands/scan.py", line 61, in run_scan
    raise ValueError('Error in scanning result code: {0}'.format(rc))
ValueError: Error in scanning result code: 1`

I have the following set:

"path_to_python": "/Users/davew/.pyenv/shims/python",
"robot_framework_workspace": "/Users/davew/code/robotframework/"

Looking at log file I get the following:

`  File "/Users/davew/Library/Application Support/Sublime Text 3/Packages/RobotFrameworkAssistant/dataparser/queue/scanner.py", line 6, in <module>
    from robot.errors import DataError
ImportError: No module named robot.errors`

**Comment by aaltat** [comment]
Based on the error,  it looks like that the your Python install doesn't contain Robot Framework installation.

**Comment by megachips** [comment]
> Based on the error, it looks like that the your Python virtual environment doesn't contain Robot Framework installation.

It does though.

`(2.7.15_robot)  davew@mac  ~/code/robotframework  pip list | grep robotframework
robotframework                3.0.4`

I can get this working if I install robotframework into my default python install but I don't want to do that - defeats the point of virtualenvs.

I have tried using the virtualenv plugin for sublime text as well to activate the virtualenv but this doesn't work either. Not sure what I can do here?

**Comment by megachips** [comment]
I can also change my default `/Users/davew/.pyenv/version` to the virtualenv and it works. However when I specify .python-version in the directory that I open sublimetext from, it defaults to the virtualenv specified by /Users/davew/.pyenv/version.

**Comment by megachips** [comment]
Okay so just changed the path in robotframework to the `"path_to_python": "/Users/davew/.pyenv/versions/2.7.15_robot/bin/python"` instead of using the shim python... would be better if the .python-version file was respected though.

**Comment by aaltat** [comment]
I understand your problem, if you think that change is important enough, please provide PR to fix it.
