### ISSUE TITLE
Creating database fails with python exception

### ISSUE THREAD

**Issue by zoltan-on-github** [andriyko/sublime-robot-framework-assistant#233]
Hi Guys,

I try to configure the plugin (by running 'Update Internal Database For Active Tab command')

I get the following exception:

```
scan_index.log:
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Sublime Text 3\Packages\Robot Framework Assistant\dataparser\run_scanner.py", line 9, in <module>
    from queue.scanner import Scanner
  File "C:\Users\xxx\AppData\Roaming\Sublime Text 3\Packages\Robot Framework Assistant\dataparser\queue\scanner.py", line 7, in <module>
    from finder import finder
ImportError: cannot import name 'finder' from 'finder' (C:\Python\Python37-32\lib\site-packages\finder\__init__.py)
```

I don't know what could be the problem here.

**Comment by aaltat** [comment]
If I recall correctly, Python 3 is not supported. There are few PR that makes Python 3 supported: 
https://github.com/andriyko/sublime-robot-framework-assistant/pull/231 and https://github.com/andriyko/sublime-robot-framework-assistant/pull/230 Unfortunately I don't have time to invest in this project in the foreseeable future.
