### ISSUE TITLE
If robot file is not in work space show better error message when indexing open tab

### ISSUE THREAD

**Issue by aaltat** [andriyko/sublime-robot-framework-assistant#55]
There is stack trace:
```
Traceback (most recent call last):
  File "SUBLIME\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "SUBLIME\Data\Packages\robotframework-from-sublime-master\commands\index_open_tab.py", line 28, in run
    db_table_name = self.get_table_name(open_tab)
  File "SUBLIME\Data\Packages\robotframework-from-sublime-master\commands\index_open_tab.py", line 80, in get_table_name
    open_tab_norm = path.normcase(open_tab)
  File "./ntpath.py", line 90, in normcase
TypeError: normcase() argument must be str or bytes, not 'NoneType'
```
It would be good to better error message to the user.

**Comment by aaltat** [comment]
This is fixed in: https://github.com/andriyko/sublime-robot-framework-assistant/commit/fe8d960f0405972b33b14d9ac5442b44a6c1eac2
